backend/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'main'
urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path("user/", include("user.urls"), name='user'),
    path("", include("taxiparty.urls"), name='taxiparty'),
]

taxiparty/urls.py
from django.urls import path
from . import views

# url config
app_name = 'taxiparty'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('createtaxiparty/', views.createTaxiParty_view, name='createtaxiparty'),
    path('taxiparty/<int:id>/', views.dynamic_lookup_view, name='taxipartydynamic'),
    path('taxiparty/<int:id>/edit/', views.party_edit_view, name='taxipartyedit'),
    path('taxiparty/<int:id>/join/', views.party_join_view, name='taxipartyjoin'),
    path('taxiparty/<int:id>/leave/', views.party_leave_view, name='taxipartyleave'),
    path('taxiparty/<int:id>/delete/', views.party_delete_view, name='taxipartydelete'),

    path('taxiparty/daily/<slug:date>/', views.daily_party_view, name='dailyparty'),
    path('taxiparty/month/<slug:yearMonth>', views.getTaxiPartyOfMonth, name='monthlytaxiparty'),

    path('createlocation/', views.create_location_view, name='createlocation'),
    path('viewlocation/', views.view_location_view, name='viewlocation'),
    path('myparty/', views.my_party_view, name='myparty'),
]

taxiride/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("taxiparty/", include("taxiparty.urls"))
]

user/urls.py
from django.urls import path
from . import views

# url config
app_name = 'user'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

taxiparty/models.py
from user.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.contrib import admin

import datetime

admin.site.register(User)

# Create your models here.
class Location(models.Model):
    name = models.TextField(blank=False, unique=True)

    def __str__(self) -> str:
        return self.name
    
class TaxiParty(models.Model):
    date = models.DateField(blank=False, default=datetime.date.today())
    time = models.TimeField(blank=False, default=datetime.time(8, 00))
    origin = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='origin')
    destination = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='destination')
    rider = models.ManyToManyField(User, related_name='rider')
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='owner')

    def clean(self):
        if self.origin == self.destination:
            raise ValidationError("Origin and destination cannot be identical")

    def getAbsoluteUrl(self):
        return reverse("taxiparty:taxipartydynamic", kwargs={"id": self.id})

    def riderInStr(self):
        riders = ""
        for rider in self.rider.all():
            riders += str(rider) + ", "
        return riders[:-2]

    def __str__(self) -> str:
        return f"{self.origin} → {self.destination}, {self.time.__str__()[:5]} {self.date.__str__()}."

taxiparty/forms.py
from django import forms

from .models import TaxiParty, Location

class TaxiPartyForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': "form-control"
            }
        )
    )

    time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                'type': 'time',
                'class': "form-control"
            }
        )
    )

    origin = forms.ModelChoiceField(
        queryset=Location.objects.all(),
        widget=forms.Select(
            attrs={
                'class': "form-select form-control"
            }
        )
    )

    destination = forms.ModelChoiceField(
        queryset=Location.objects.all(),
        widget=forms.Select(
            attrs={
                'class': "form-select form-control"
            }
        )
    )

    class Meta:
        model = TaxiParty
        fields = [
            'date',
            'time',
            'origin',
            'destination',
        ]

    def save(self, commit=True):
        instance = super(TaxiPartyForm, self).save(commit=False)
        instance.origin = self.cleaned_data['origin']
        instance.destination = self.cleaned_data['destination']
        if commit:
            instance.save()
        return instance

class LocationForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': "form-control"
            }
        )
    )
    
    class Meta:
        model = Location
        fields = [
            'name'
        ]

taxiparty/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import Http404
from django_user_agents.utils import get_user_agent

from rest_framework.response import Response
from rest_framework.decorators import api_view

from .models import TaxiParty, Location
from .forms import TaxiPartyForm, LocationForm
from .serializers import TaxiPartySerializer

import datetime
import time

# Create your views here.
def createTaxiParty_view(request):
    user_agent = get_user_agent(request)

    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    form = TaxiPartyForm(request.POST or None)

    # if request.method == 'POST':
    if form.is_valid():
        party = form.save()
        party.rider.add(request.user)
        party.owner = request.user
        party.save()
        return redirect(reverse('taxiparty:taxipartydynamic', kwargs={"id": party.id}))

    locations = Location.objects.all()

    context = {
        'mobile': user_agent.is_mobile,
        'form': form,
        'locations': locations,
    }
    return render(request, "createtaxiparty.html", context)

def create_location_view(request):
    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    form = LocationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(reverse('taxiparty:home'))
    user_agent = get_user_agent(request)

    context = {
        'form': form,
        'mobile': user_agent.is_mobile
    }
    return render(request, "create_location.html", context)

def home_view(request):
    user_agent = get_user_agent(request)

    context = {
        'mobile': user_agent.is_mobile
    }

    if user_agent.is_mobile:
        return render(request, "mobile_taxipartyhome.html", context)
    elif user_agent.is_pc:
        return render(request, "taxipartyhome.html", context)



def view_location_view(request):
    locationList = Location.objects.all()
    user_agent = get_user_agent(request)

    context = {
        "locationList": locationList,
        'mobile': user_agent.is_mobile
    }
    return render(request, "view_location.html", context)

def dynamic_lookup_view(request, id):
    obj = get_object_or_404(TaxiParty, id=id)
    joinable = (request.user not in obj.rider.all())
    editable = (request.user == obj.owner)
    anon = request.user.is_anonymous
    user_agent = get_user_agent(request)

    context = {
        "party": obj,
        "editable": editable,
        "joinable": joinable,
        "anon": anon,
        'mobile': user_agent.is_mobile
    }
    return render(request, "partydetail.html", context)

def party_edit_view(request, id):
    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    obj = get_object_or_404(TaxiParty, id=id)
    if request.user != obj.owner:
        messages.info(request, 'You are not the owner of the Taxi Party!')
        return redirect(reverse('taxiparty:taxipartydynamic', kwargs={'id': id}))
    if request.method == 'POST':
        form = TaxiPartyForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('taxiparty:taxipartydynamic', kwargs={'id': id}))
    else:
        form = TaxiPartyForm(instance=obj)

    user_agent = get_user_agent(request)
    
    context = {
        'form': form,
        'mobile': user_agent.is_mobile
    }
    return render(request, 'edit_party.html', context)

def party_join_view(request, id):
    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    joiner = request.user
    obj = get_object_or_404(TaxiParty, id=id)
    obj.rider.add(joiner)
    if obj.owner == None:
        obj.owner = joiner
    obj.save()
    return redirect(reverse('taxiparty:taxipartydynamic', kwargs={'id': id}))

def party_leave_view(request, id):
    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    obj = get_object_or_404(TaxiParty, id=id)
    riders = obj.rider.all()
    if request.user not in riders:
        messages.info(request, 'You are not part of the Taxi Party!')
        return redirect(reverse('taxiparty:taxipartydynamic', kwargs={'id': id}))
    else:
        leavingUser = request.user
        obj.rider.remove(leavingUser)
        riders = obj.rider.all()
        if obj.owner == leavingUser and len(obj.rider.all()) == 0:
            obj.owner = None
        elif obj.owner == leavingUser:
            obj.owner = riders[0]
        obj.save()
        return redirect(reverse('taxiparty:home'))

def my_party_view(request):
    if request.user.is_anonymous:
        return redirect(reverse('user:login'))
    myParties = TaxiParty.objects.filter(rider=request.user)
    user_agent = get_user_agent(request)

    context = {
        'mobile': user_agent.is_mobile,
        'partyList': myParties
    }
    return render(request, "myparty.html", context)

def daily_party_view(request, date: str):
    user_agent = get_user_agent(request)

    try:
        year, month, day = [int(x) for x in date.split('-')]
        dateInDateTime = datetime.date(year, month, day)
        myParties = TaxiParty.objects.filter(date=dateInDateTime)
        context = {
            'date': dateInDateTime.__str__(),
            'partyList': myParties,
            'mobile': user_agent.is_mobile
        }
    except:
        messages.info(request, 'Oops! Wrong Date Entered! Please enter a valid date.')
        context = {
            'mobile': user_agent.is_mobile,
            'partyList': []
        }

    return render(request, "dailyparty.html", context)

def party_delete_view(request, id):
    if request.user.is_anonymous or not request.user.is_superuser:
        raise Http404
    party = get_object_or_404(TaxiParty, id=id)
    party.delete()
    return redirect(reverse('taxiparty:home'))


# @api_view(['REMOVE'])

@api_view(['GET'])
def getTaxiPartyOfMonth(request, yearMonth):
    try:
        testYearMonth = str(yearMonth)
        testYearMonth += "-01"
        format = "%Y-%m-%d"
        time.strptime(testYearMonth, format)
    except:
        raise Http404
    party = TaxiParty.objects.all().filter(date__contains=str(yearMonth))
    serializer = TaxiPartySerializer(party, many=True)
    return Response(serializer.data)

taxiparty/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>USAG Humphreys Taxi Party</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"/>





    
</head>
<body>
    {% if mobile %}
        <link rel="stylesheet" href="{% static 'css/mobile_mystyle.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    {% endif %}

    {% include 'navbar.html' with request=request %}
    <div class="main-container">
        {% block content %}
            <!-- Your content goes here -->
        {% endblock %}
    </div>

</body>
</html>

taxiparty/templates/calendar.html
{% block content %}
{% load static %}

<script src="static/js/viewparty.js" type="text/javascript"></script>
<script src="static/js/calenderjs.js" type="text/javascript"></script>


<body>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"/>
    <div class="calender_container" style="max-width:100%;">
     

            <div class="month-selector">
                <div class="calendar_button_container">
                    <button class="month_button" onclick="prevMonth()"><i class="fas fa-chevron-left"></i></button>
                    <div class="calendar_month" id="currentMonthYear">month</div>

                    <button class="month_button" onclick="nextMonth()"><i class="fas fa-chevron-right"></i></button>
                </div>
            </div>
            <div style="display: flex; align-items: center;
            justify-content: center; ">
                <button onclick="goBacktoToday()" style="font-size: small; background-color: rgba(6, 124, 202, 0.644); overflow: hidden; border-radius: 10px; color: white;"> Go back to today </button>
            </div>
    
            <table id="calendar">
                <thead>
                    <tr>
                        <th>Sun</th>
                        <th>Mon</th>
                        <th>Tue</th>
                        <th>Wed</th>
                        <th>Thu</th>
                        <th>Fri</th>
                        <th>Sat</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
       
    <div>
</body>

<script>
    window.onload = function() {
        get_monthinfo(0, 0, updateCalendar);
    };
</script>
{% endblock %}

taxiparty/templates/create_location.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h3 class="home-title">Create New Location</h1>
    <hr>
    
    <div class="login-container">
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="sec-button">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

taxiparty/templates/createtaxiparty.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="home-title">Create New Taxi Party</h1>
    <hr>
    <div class="login-container">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button class="sec-button">Save</button>
        </form>
    </div>
   
</div>
{% endblock %}

taxiparty/templates/delete_party.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <form method='POST'>{% csrf_token %}
        <h1 class="mb-4">
            Do you want to delete the following Taxi Party?
        </h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">
                    <strong>{{ party }}</strong><br>
                    {{ party.riderInStr }}
                </p>
            </div>
        </div>
        <div class="mt-4">
            <input type='submit' class="btn btn-danger mr-2" value="Yes" /> 
            <a href='../' class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

taxiparty/templates/edit_party.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="home-title">Edit Taxi Party Details</h1>
    <hr>
    <div class="login-container">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="sec-button">Save</button>
        </form>
    </div>
</div>
{% endblock %}

taxiparty/templates/mobile_calendar.html
{% block content %}
{% load static %}

<script src="static/js/viewparty.js" type="text/javascript"></script>
<script src="static/js/calenderjs_mobile.js" type="text/javascript"></script>

<body>
    <div class="calendar_container" style="max-width:100%;">
        <div class="calendar_button_container">
            <button class="month_button" onclick="prevMonth()"><i class="fas fa-chevron-left"></i></button>
             <div class="calendar_month" id="currentMonthYear">month</div>
            <button class="month_button" onclick="nextMonth()"><i class="fas fa-chevron-right"></i></button>
        </div>
        <button class="backToToday-button" onclick="goBacktoToday()"> Go back to today </button>
        <table id="calendar">
            <thead>
                <tr>
                    <th>Sun</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    <th>Sat</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

</body>

<script>
    window.onload = function() {
        get_monthinfo(0, 0, updateCalendar);
    };
</script>
{% endblock %}

taxiparty/templates/mobile_taxipartyhome.html
{% extends 'base.html' %}

{% block content %}

<head>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="/static/js/viewparty.js"></script>
    <script src="/static/js/calenderjs.js" type="text/javascript"></script> 
</head>

<h1 class="home-title">Taxi Party Calendar</h1>
<hr>
<div class="homepage-container">

    {% include 'mobile_calendar.html' %}
    
    <div class="partyList_container">
        <h2 style="text-align: center; width: 100%;" id="partyListTitle">  </h2>
        <div class="partyList" id="partyList">

        </div>
    </div>
</div>
{% endblock %}

taxiparty/templates/myparty.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="home-title">My Taxi Parties</h1>
    <hr>
    <div class="login-container" style="justify-items: center;">
        {% for party in partyList %}
        <div class="party-row">
            <a href="{{ party.getAbsoluteUrl }}" class="text-decoration-none">{{ party }}</a>
        </div>
        {% endfor %}
    </div>

{% endblock %}

taxiparty/templates/navbar.html
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"/>

<nav class="navbar navbar-expand-lg">
    <div class="container" style="display: flex; flex-direction: column;"> 
        <a class="navbar-brand" href="{% url 'taxiparty:home' %}">USAG Humphreys Taxi Party</a>

        <div class="navbar-nav mx-auto" style="display: flex; flex-direction: row; text-align: center; justify-content: center;">
            {% if request.user.is_authenticated %}
            <div style="flex: 1; flex-direction: column;">
                <p style="text-align: center; color: white; margin-bottom: 0%;">Welcome {{ request.user.username }}!</p>
                <div >
                    <a class="nav-link" style="padding-top: 0;" href="{% url 'user:logout' %}">Logout</a>
                </div>
            </div>
            {% else %}
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'user:signup' %}">Signup</a>
                </div>
                {% endif %}
                
            {% if mobile %}
                <button onclick="myFunction()" class="sec-button dropbtn"> Menu</button>
            {% endif %}
            </div>
        {% if mobile %}
        <div id="myDropdown" class="dropdown-content">
          <a href="{% url 'taxiparty:createtaxiparty' %}">Create Taxi Party</a>
          <a href="{% url 'taxiparty:viewlocation' %}">View Humphreys Locations</a>
          <a href="{% url 'taxiparty:createlocation' %}">Create USAG Humphreys Locations</a>
          <a href="{% url 'taxiparty:myparty' %}">View My Taxi Parties</a>
        </div>
        {% else %}
        <div class="navbar-menu">
            <div class="navbar-menu-item">
                <a href="{% url 'taxiparty:createtaxiparty' %}">Create Taxi Party</a>
            </div>
            <div class="navbar-menu-item">
                <a href="{% url 'taxiparty:viewlocation' %}">View Humphreys Locations</a>
            </div>
            <div class="navbar-menu-item">
                <a href="{% url 'taxiparty:createlocation' %}">Create USAG Humphreys Locations</a>
            </div>
            <div class="navbar-menu-item">
                <a href="{% url 'taxiparty:myparty' %}">View My Taxi Parties</a>
            </div>
        </div>
        <!-- <ul class="navbar-nav mx-auto" style="text-align: center">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'taxiparty:createtaxiparty' %}">Create Taxi Party</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'taxiparty:viewlocation' %}">View Humphreys Locations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'taxiparty:createlocation' %}">Create USAG Humphreys Locations</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'taxiparty:myparty' %}">View My Taxi Parties</a>
            </li>
        </ul>        -->
        {% endif %}
    </div>
</nav>

<script>
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown menu if the user clicks outside of it
    window.onclick = function(event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }   
    }
</script>

taxiparty/templates/partydetail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="home-title">Taxi Party Details</h1>
    <hr>
    {% if anon %}
        <h5>Log In to Join Taxi Party!</h5>
    {% endif %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div style="margin-bottom: 4%;">
        <div class="login-container" style="padding-top: 4%; padding-bottom: 4%;">

            <h5 class="home-title">Party Information</h5>
            <p class="card-text">Party Name: </br> {{ party }}</p>
            <p class="card-text">Riders: {{ party.riderInStr }}</p>
            <p class="card-text">Party Owner: {{ party.owner }}</p>
            <!-- Add more party details as needed -->
  
        </div>
    </div>
    <div class="login-container">
        <h5 class="home-title">Actions</h5>
        <div>
            {% if anon %}
            <div class="party-row">Log In to Join Party!</div>
            {% endif %}
            {% if editable %}
            <div class="party-row link"><a href='./edit/'>Edit Party Details</a></div>
            {% endif %}
            {% if joinable and not anon %}
            <div class="party-row link"><a href='./join/'>Join Party</a></div>
            {% endif %}
            {% if not joinable and not anon %}
            <div class="party-row warning"><a href='./leave/'>Leave Party</a></div>
            {% endif %}
            {% if user.is_superuser %}
            <div class="party-row warning"><a href='./delete/'>Delete Party</a></div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

taxiparty/templates/taxipartyhome.html
{% extends 'base.html' %}

{% block content %}

<head>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="/static/js/viewparty.js"></script>
    <script src="/static/js/calenderjs.js" type="text/javascript"></script> 
</head>

<div class="homepage-container">

    <h1 style="text-align: center; padding: 1%; margin_bottom: 5px; background-color: rgba(0, 0, 0, 0);">Taxi Party Calendar</h1>

    {% include 'calendar.html' %}

</div>
{% endblock %}

taxiparty/templates/view_location.html
{% extends 'base.html' %}

{% block content %}

<div class="container-lg"> <!-- Adjusting the container to container-lg -->
    <div class="row justify-content-center">
        <div class="align-items-center" style="width: 90%;"> <!-- Adjusting the width of the content -->
            <h2 class="home-title">USAG Humphreys Locations</h2>
            <hr>
            <div class="login-container"> <!-- Adjusting the width of the list -->
                {% for location in locationList %}
                    <div class="party-row">
                        {{ location }}
                    </div>
                {% endfor %}
                </div>
        </div>
    </div>
</div>




    

{% endblock %}

taxiparty/templates/viewtaxiparty.html
<ul class="list-group">

</ul>